<a href="https://colab.research.google.com/github/Anand0111/MLInfidata/blob/main/MLAssignment1(Mean).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [89]:
import pandas as pd
import numpy as np
from sklearn import linear_model
df=pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [90]:
df.rename({'test_score(out of 10)': 'test_score'},inplace=True,axis=1)
df.rename({'interview_score(out of 10)': 'interview_score'},inplace=True,axis=1)
df.rename({'salary($)': 'salary'},inplace=True,axis=1)
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [91]:
df.experience[2]=5
df.experience[3]=2
df.experience[4]=7
df.experience[5]=3
df.experience[6]=10
df.experience[7]=11

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid 

In [92]:
df.experience.mean()

6.333333333333333

In [93]:
df.test_score.mean()

7.857142857142857

In [94]:
df.experience=df.experience.fillna(df.experience.mean())
df.test_score=df.test_score.fillna(df.test_score.mean())
df

experience  test_score  interview_score  salary
0    6.333333    8.000000                9   50000
1    6.333333    8.000000                6   45000
2    5.000000    6.000000                7   60000
3    2.000000   10.000000               10   65000
4    7.000000    9.000000                6   70000
5    3.000000    7.000000               10   62000
6   10.000000    7.857143                7   72000
7   11.000000    7.000000                8   80000

In [95]:
reg=linear_model.LinearRegression()
reg.fit(df.drop('salary', axis='columns'),df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [96]:
reg.coef_

array([2633.0537639 , 1203.95910777, 2787.82004231])

In [97]:
inter=reg.intercept_

In [98]:
reg.predict([[10,7,7]])

array([69183.22298109])

In [99]:
reg.predict([[6,8,6]])

array([57067.14699096])

In [100]:
2633.0537639*10 +1203.95910777*7+2787.82004231*7+inter

69183.22298110495