<a href="https://colab.research.google.com/github/Anand0111/MLInfidata/blob/main/MLAssignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import pandas as pd
import numpy as np
from sklearn import linear_model
df=pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [62]:
df.rename({'test_score(out of 10)': 'test_score'},inplace=True,axis=1)
df.rename({'interview_score(out of 10)': 'interview_score'},inplace=True,axis=1)
df.rename({'salary($)': 'salary'},inplace=True,axis=1)
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [63]:
df.experience[2]=5
df.experience[3]=2
df.experience[4]=7
df.experience[5]=3
df.experience[6]=10
df.experience[7]=11

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid 

In [64]:
df.experience.median()

6.0

In [65]:
df.test_score.median()

8.0

In [66]:
df.experience=df.experience.fillna(df.experience.median())
df.test_score=df.test_score.fillna(df.test_score.median())
df

experience  test_score  interview_score  salary
0         6.0         8.0                9   50000
1         6.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         8.0                7   72000
7        11.0         7.0                8   80000

In [67]:
reg=linear_model.LinearRegression()
reg.fit(df.drop('salary', axis='columns'),df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [68]:
reg.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [69]:
reg.intercept_

11869.91869918695

In [73]:
reg.predict([[10,8,6]])

array([68227.64227642])

In [71]:
reg.predict([[6,8,6]])

array([56975.6097561])

In [74]:
2813.00813008*10+ 1333.33333333*8+ 2926.82926829*6+11869.91869918695

68227.64227636694